// playlist_arabic.js
const arabicPlaylist = [
  {
    name: "Aisyah Istri Rasulullah",
    artist: "Anisa Rahman",
    src: "arabic/aisyah istri rasulullah.mp3",
    cover: "cover/anisa rahman.png",
  },
  {
    name: "Al Hijrotu",
    artist: "Adzando Davema",
    src: "arabic/al hijrotu.mp3",
    cover: "cover/adzando davema.png",
  },
   {
    name: "Allahi Allah Kiya Karo",
    artist: "Maher Zain",
    src: "arabic/allahi allah kiya karo.mp3",
    cover: "cover/maher zain.png",
  },
  {
    name: "Assalamu'alaika",
    artist: "Maher Zain",
    src: "arabic/assalamu'alaika.mp3",
    cover: "cover/maher zain.png",
  },
  {
    name: "Casablanca",
    artist: "Nuha Bahrin, Naufal Azrin",
    src: "arabic/casablanca.mp3",
    cover: "cover/casablanca.png",
  },
  {
    name: "Deen Assalam",
    artist: "Nissa Sabyan",
    src: "arabic/deen assalam.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Ghannili",
    artist: "Safia Rahma",
    src: "arabic/ghannili.mp3",
    cover: "cover/safia rahma.png",
  },
   {
    name: "Hadal Ahbek",
    artist: "Issam Alnajjar",
    src: "arabic/hadal ahbek.mp3",
    cover: "cover/issam alnajjar.png",
  },
  {
    name: "Huwannur",
    artist: "Ai Khodijah",
    src: "arabic/huwannur.mp3",
    cover: "cover/ai khodijah.png",
  },
  {
    name: "Insyaallah",
    artist: "Maher Zain",
    src: "arabic/insyaallah.mp3",
    cover: "cover/maher zain.png",
  },
  {
    name: "Kalam Eineh",
    artist: "Sherine",
    src: "arabic/kalam eineh.mp3",
    cover: "cover/sherine.png",
  },
   {
    name: "Kun Anta",
    artist: "Aseer Ahsan",
    src: "arabic/kun anta.mp3",
    cover: "cover/aseer ahsan.png",
  },
  {
    name: "Man Ana",
    artist: "Hadi Assegaf",
    src: "arabic/man ana.mp3",
    cover: "cover/Hadi Assegaf.png",
  },
  {
    name: "Muhammad Nabiku",
    artist: "Hadad Alwi",
    src: "arabic/muhammad nabiku.mp3",
    cover: "cover/hadad alwi.png",
  },
  {
    name: "Muhammad Nabina",
    artist: "Hamada Helal",
    src: "arabic/muhammad nabina.mp3",
    cover: "cover/hamada helal.png",
  },
   {
    name: "Nabi Putra Abdullah",
    artist: "Ayu Dewi",
    src: "arabic/nabi putra abdullah.mp3",
    cover: "cover/ayu dewi.png",
  },
  {
    name: "Nas Teshbehlena",
    artist: "Maher Zain",
    src: "arabic/nas teshbehlena.mp3",
    cover: "cover/maher zain.png",
  },
  {
    name: "Natawassal Bil Hubabah",
    artist: "Mazro",
    src: "arabic/natawassal bil hubabah.mp3",
    cover: "cover/mazro.png",
  },
  {
    name: "Qomarun",
    artist: "Nissa Sabyan",
    src: "arabic/qomarun.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Rahmatun Lil'alameen",
    artist: "Maher Zain",
    src: "arabic/rahmatun lil'alameen.mp3",
    cover: "cover/Maher Zain.png",
  },
   {
    name: "Rindu Muhammadku",
    artist: "Hadad Alwi",
    src: "arabic/rindu muhammadku.mp3",
    cover: "cover/hadad alwi.png",
  },
  {
    name: "Rohman Ya Rohman",
    artist: "Nissa Sabyan",
    src: "arabic/rohman ya rohman.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Wahdana Dana",
    artist: "Wafiq Azizah",
    src: "arabic/wahdana dana.mp3",
    cover: "cover/wafiq azizah.png",
  },
  {
    name: "Ya Asyiqol Musthofa",
    artist: "Nissa Sabyan",
    src: "arabic/ya asyiqol musthofa.mp3",
    cover: "cover/nissa sabyan.png",
  },
   {
    name: "Ya Habibal Qolbi",
    artist: "Nissa Sabyan",
    src: "arabic/ya habibal qolbi.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Ya Jamalu",
    artist: "Nissa Sabyan",
    src: "arabic/ya jamalu.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Ya Maulana",
    artist: "Nissa Sabyan",
    src: "arabic/ya maulana.mp3",
    cover: "cover/nissa sabyan.png",
  },
  {
    name: "Ya Nabi Salam 'Alayka",
    artist: "Maher Zain",
    src: "arabic/ya nabi salam alayka.mp3",
    cover: "cover/maher zain.png",
  },
   {
    name: "Ya Tarim",
    artist: "Aishwa Nahla",
    src: "arabic/ya tarim.mp3",
    cover: "cover/aishwa nahla.png",
  },
  {
    name: "Yasir Lana (Ilahana)",
    artist: "Ai Khodijah",
    src: "arabic/yasir lana (Ilahana).mp3",
    cover: "cover/ai khodijah.png",
  },
];
