// playlist_old.js
const oldPlaylist = [
  {
    name: "All About That Bass",
    artist: "Band Legendaris",
    src: "old/all about that bass.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Awing Mawek",
    artist: "Maestro Gitar",
    src: "old/awing mawek.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Believer",
    artist: "Band Legendaris",
    src: "old/believer.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Despacito",
    artist: "Maestro Gitar",
    src: "old/despacito.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Aku Suka Body Aisyah",
    artist: "Band Legendaris",
    src: "old/dj aku suka body aisyah.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Bermain Dubstep",
    artist: "Maestro Gitar",
    src: "old/dj bermain dubstep.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Don't Watch Me Cry",
    artist: "Band Legendaris",
    src: "old/dj don't watch me cry.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Emang Mantul Punya Istri Dua",
    artist: "Maestro Gitar",
    src: "old/dj emang mantul punya istri dua.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Entah Apa Yang Merasukimu",
    artist: "Band Legendaris",
    src: "old/dj entah apa yang merasukimu.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Everything At Once",
    artist: "Maestro Gitar",
    src: "old/dj everything at once.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Haruskah Berakhir",
    artist: "Band Legendaris",
    src: "old/dj haruskah berakhir.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Harusnya Aku",
    artist: "Maestro Gitar",
    src: "old/dj harusnya aku.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Kusimpan Rindu Di hati",
    artist: "Band Legendaris",
    src: "old/dj kusimpan rindu di hati.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Mungkin Sang Fajar",
    artist: "Maestro Gitar",
    src: "old/dj mungkin sang fajar.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Pong Pong",
    artist: "Band Legendaris",
    src: "old/dj pong pong.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Satu Hati Sampai Mati",
    artist: "Maestro Gitar",
    src: "old/dj satu hati sampai mati.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Simphony Kaweni",
    artist: "Band Legendaris",
    src: "old/dj simphony kaweni.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Slow Make It Bun Dem",
    artist: "Maestro Gitar",
    src: "old/dj slow make it bun dem.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Sungguh Ku Merasa Resah",
    artist: "Band Legendaris",
    src: "old/dj sungguh ku merasa resah.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Dj Trouble Is A Friends",
    artist: "Maestro Gitar",
    src: "old/dj trouble is a friends.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Dj Walaupun Terbentang Jarak",
    artist: "Maestro Gitar",
    src: "old/dj walaupun terbentang jarak.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Don't Let Me Down",
    artist: "Band Legendaris",
    src: "old/don't let me down.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Girls Like You",
    artist: "Maestro Gitar",
    src: "old/girls like you.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
  {
    name: "Payphone",
    artist: "Band Legendaris",
    src: "old/payphone.mp3",
    cover: "https://picsum.photos/200/200?random=4",
  },
  {
    name: "Waka Waka",
    artist: "Maestro Gitar",
    src: "old/waka waka.mp3",
    cover: "https://picsum.photos/200/200?random=5",
  },
];
