// File: aku ikhlas.js
lyricsData = [
  { time: 0, text: "--- Aftershine feat. Damara De ---" },
  { time: 17.13, text: "Aku nglakoni kabeh iki" },
  { time: 28.28, text: "Ikhlas seko ning ati" },
  { time: 33.35, text: "Nggo sliramu" },
  { time: 41.91, text: "Duh kang mas sepurane yen aku" },
  { time: 53.69, text: "Nggawe loro atimu" },
  { time: 58.51, text: "Aku ora menghargai" },
  { time: 63.53, text: "Koe sing gemati" },
  { time: 69.93, text: "Yowes rapopo rasah digetuni" },
  { time: 77.19, text: "Cukup aku ngerti perjuanganku" },
  { time: 84.11, text: "Dadi esemmu ning uripmu" },
  { time: 93.89, text: "Sak jembare segoro aku ikhlas" },
  { time: 98.83, text: "Yen akhire kudu nompo loro iki" },
  { time: 108.45, text: "Tulung ojo koe ninggalke aku" },
  { time: 114.18, text: "Aku pengen ning sandingmu" },
  { time: 148.19, text: "Yowes rapopo rasah digetuni" },
  { time: 154.83, text: "Cukup aku ngerti perjuanganku" },
  { time: 162.46, text: "Dadi esemmu ning uripmu" },
  { time: 171.64, text: "Sak jembare segoro aku ikhlas" },
  { time: 176.90, text: "Yen akhire kudu nompo loro iki" },
  { time: 186.42, text: "Tulung ojo koe ninggalke aku" },
  { time: 192.39, text: "Aku pengen ning sandingmu" },
  { time: 201.02, text: "Pancen iki dalane, tak tompo aku wis iso nerimo" },
  { time: 210.13, text: "Tapi aku sing ora lilo" },
  { time: 217.58, text: "Pengenku nyanding koe" },
  { time: 221.27, text: "Wes lalekke aku, tak cobo nompo anane" },
  { time: 230.65, text: "Pancen dudu takdire" },
  { time: 234.93, text: "Mungkin wis takdire kudu dikuatke" },
  { time: 238.88, text: "Nompo kenyataane aku ro koe" },
  { time: 250.03, text: "Pancen dudu jodone" },
  { time: 260.00, text: "--- Selesai ---" }
];
