// File: jawa/angel.js
lyricsData = [
  { time: 0, text: "--- Yeni Inka - Angel ---" },
  { time: 0.75, text: "Ketika semuanya terasa begitu abot" },
  { time: 8.34, text: "Ku coba untuk tetap rapopo" },
  { time: 15.91, text: "Di saat cinta ini terasa angel" },
  { time: 24.56, text: "Angel..." },
  { time: 31.08, text: "(Aneka Safari Record)" },
  { time: 46.23, text: "Tresno kuwi ra koyo instagram" },
  { time: 53.06, text: "Seng diklik langsung oleh ati" },
  { time: 59.65, text: "Duh gusti nopo kulo di prank" },
  { time: 67.3, text: "Ra kuat ati iki pas dee medot janji" },
  { time: 76.32, text: "Ayumu tenanan ora editan" },
  { time: 84.77, text: "Seng marai aku kedanan" },
  { time: 91.57, text: "Pancen salahku dewe ra ono seng ngongkon" },
  { time: 99.36, text: "Abot sanggane aku angel move on" },
  { time: 108.26, text: "Ketika semuanya terasa begitu abot" },
  { time: 115.51, text: "Ku coba untuk tetap rapopo" },
  { time: 122.87, text: "Di saat cinta ini terasa angel" },
  { time: 130.73, text: "Angel..." },
  { time: 136.21, text: "Ku katakan dalam hati yo uwes" },
  { time: 143.87, text: "Menurutmu aku kudu piye" },
  { time: 150.65, text: "Apakah aku harus mengikutimu" },
  { time: 157.23, text: "Yo aku mengkis mengkis" },
  { time: 164.0, text: "(Mengkis mengkis toh mas)" },
  { time: 167.96, text: "(Adela!)" },
  { time: 192.51, text: "Ayumu tenanan ora editan" },
  { time: 199.67, text: "Seng marai aku kedanan" },
  { time: 205.92, text: "Pancen salahku dewe ra ono seng ngongkon" },
  { time: 213.36, text: "Abot sanggane aku angel move on" },
  { time: 221.78, text: "Ketika semuanya terasa begitu abot" },
  { time: 229.7, text: "Ku coba untuk tetap rapopo" },
  { time: 236.17, text: "Di saat cinta ini terasa angel" },
  { time: 243.7, text: "Angel..." },
  { time: 249.53, text: "Ku katakan dalam hati yo uwes" },
  { time: 257.12, text: "Menurutmu aku kudu piye" },
  { time: 264.21, text: "Apakah aku harus mengikutimu" },
  { time: 270.79, text: "Yo aku mengkis mengkis..." },
  { time: 282.76, text: "--- Selesai ---" }
];
