// File: angin dalu.js
lyricsData = [
  { time: 0, text: "--- NDX A.K.A - Angin Dalu ---" },
  { time: 0.74, text: "Dek masio sainganku koncoku dewe" },
  { time: 4.50, text: "Sugih-sugih luwih ganteng seko aku" },
  { time: 7.41, text: "Aku panggah ra mundur dek" },
  { time: 9.49, text: "Modal nekat mencintaimu, los sak kabehe" },
  { time: 13.22, text: "Pokoke aku tetep panggah mencintaimu" },
  { time: 17.02, text: "Wani ngeyel, dek, wani nekat, wani ajur demi kowe" },
  { time: 21.90, text: "Tresno ning njero dodo" },
  { time: 25.44, text: "Sing tak jaluk imbangono" },
  { time: 29.35, text: "Masio aku ra sugih bondo" },
  { time: 33.51, text: "Moh yen digawe loro" },
  { time: 37.52, text: "Sak pedhote nafasku mung kowe sing tak tunggu" },
  { time: 45.02, text: "Ora ono liyane sing ning atiku" },
  { time: 52.96, text: "Sak enteke nyawaku ora ngaleh tresnaku" },
  { time: 60.42, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 68.27, text: "Nduweku mung roso tresno, dudu setumpuk bondo" },
  { time: 72.30, text: "Nekat mencintaimu kuwi wes dadi prinsipku" },
  { time: 76.30, text: "Ngenehi perhatian, ngenehi kasih sayang" },
  { time: 79.76, text: "Berjalannya waktu mugo-mugo kowe dadi nyaman" },
  { time: 83.58, text: "Cintaku wes kadung mapan, penuh doa harapan" },
  { time: 87.80, text: "Berpaling dari hatimu itu tidak akan" },
  { time: 91.55, text: "Nek ra kowe ra wae, aku emoh liyane" },
  { time: 95.45, text: "Tetep konsisten mencintaimu selawase" },
  { time: 99.14, text: "Sak pedhote nafasku mung kowe sing tak tunggu" },
  { time: 106.55, text: "Ora ono liyane sing ning atiku" },
  { time: 114.25, text: "Sak enteke nyawaku ora ngaleh tresnaku" },
  { time: 121.88, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 129.74, text: "Aku panggah tetep ngeyel masio cinta kowe angel" },
  { time: 133.71, text: "Ra urusan sainganku mung konco cedhakku" },
  { time: 137.67, text: "Aku ra bakal mundur, ati wes kadung njegur" },
  { time: 141.32, text: "Wani ngeyel, wani perih, wani mumet, wani ajur" },
  { time: 144.92, text: "Sak pedote nafas iki, sak enteke nyowo iki" },
  { time: 148.94, text: "Tresnoku ra pindah ati, dirimu sing tak tenani" },
  { time: 152.86, text: "Janji bakalan tak jogo nganti nyowo ini lungo" },
  { time: 156.68, text: "Tresnoku ora mungkin, ora mungkin ngeliyo" },
  { time: 160.40, text: "Sing tak suwun mung siji, kowe sing gemati" },
  { time: 167.98, text: "Jogonen ati iki, ojo nganti aku mbok larani" },
  { time: 175.72, text: "Tulung jaganen aku, tulung jogo tresnoku" },
  { time: 183.22, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 191.29, text: "Sak pedhote nafasku mung kowe sing tak tunggu" },
  { time: 198.79, text: "Ora ono liyane sing ning atiku" },
  { time: 206.41, text: "Sak enteke nyawaku ora ngaleh tresnaku" },
  { time: 214.01, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 221.86, text: "Sak pedhote nafasku mung kowe sing tak tunggu" },
  { time: 229.44, text: "Ora ono liyane sing ning atiku" },
  { time: 237.16, text: "Sak enteke nyawaku ora ngaleh tresnaku" },
  { time: 244.63, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 252.45, text: "Ademe angin dalu dadi saksi bisu" },
  { time: 260.00, text: "--- Selesai ---" }
];
