// File: apa kabar mantan.js
lyricsData = [
  { time: 0, text: "--- NDX A.K.A - Apa Kabar Mantan ---" },
  { time: 16.64, text: "Apa kabar wong sing tau tak sayang?" },
  { time: 20.28, text: "Apa kabar wong sing tau tak gawe nyaman?" },
  { time: 24.15, text: "Susah-seneng janjine bebarengan" },
  { time: 27.89, text: "Ning akhire, kowe lunga ninggal kenangan" },
  { time: 31.72, text: "Atiku ra bakal serapuh kuwi" },
  { time: 35.68, text: "Masalah percintaan, tak pikir keri" },
  { time: 39.53, text: "Masa lalu ra perlu tak baleni" },
  { time: 43.08, text: "Teka tenang, kabeh uwis tak gawe lali" },
  { time: 49.15, text: "Hei, apa kabar mantanku sing tau neng atiku?" },
  { time: 52.93, text: "Kelingan ra karo aku sing tau ngisi atimu" },
  { time: 57.07, text: "Mbiyen bubare merga kowe ana sing liyane" },
  { time: 60.57, text: "Waton minggat ninggal lunga aku sing ana ning kene" },
  { time: 64.85, text: "Tangise ati iki merga kowe sing jalari" },
  { time: 68.46, text: "Bahagiaku hancur ketika tresna iki dibagi" },
  { time: 72.56, text: "Cerita cinta sing tak bangun nganti tiba tangi" },
  { time: 76.05, text: "Terima kasih luka ini, sekian, ku pamit pergi" },
  { time: 79.86, text: "Apa kabar wong sing tau tak sayang?" },
  { time: 83.62, text: "Apa kabar wong sing tau tak gawe nyaman?" },
  { time: 87.49, text: "Susah-seneng janjine bebarengan" },
  { time: 91.03, text: "Ning akhire, kowe lunga ninggal kenangan" },
  { time: 95.35, text: "Atiku ra bakal serapuh kuwi" },
  { time: 99.04, text: "Masalah percintaan, tak pikir keri" },
  { time: 102.88, text: "Masa lalu ra perlu tak baleni" },
  { time: 106.43, text: "Teka tenang, kabeh uwis tak gawe lali" },
  { time: 112.72, text: "Ra isa dibaleni, getun kuwi tiba mburi" },
  { time: 116.24, text: "Kuwi mbiyen ra kelingan pa pas aku mbok larani" },
  { time: 120.30, text: "Saiki kowe ngemis njaluk aku akon bali" },
  { time: 124.28, text: "Ya, sorry, sepurane ati iki wis ra sudi" },
  { time: 127.97, text: "Saiki lungamu ora bakalan tak gondeli" },
  { time: 131.63, text: "Apa maneh ora mungkin nganti kowe tak tangisi" },
  { time: 135.83, text: "Sementara tak ngene wae, aku dhewe wani" },
  { time: 139.62, text: "Matur sembah nuwun sanget sampun nate nglarani" },
  { time: 143.51, text: "Mas, kang mas, sing sepurane tenan" },
  { time: 147.09, text: "Mbiyen tau nggawe atimu kelaran" },
  { time: 151.01, text: "Tak kira dek'e iki luwih sayang" },
  { time: 154.53, text: "Jebul akhire, tresnaku nggo dolanan" },
  { time: 158.87, text: "Pa ra krasa sampeyan tak kangeni" },
  { time: 162.46, text: "Pengen dadi siji, kabeh dibaleni?" },
  { time: 166.42, text: "Tulung ngertio isi ati iki" },
  { time: 170.12, text: "Sumpah matiku, ra bakal tak larani" },
  { time: 173.99, text: "Apa kabar wong sing tau tak sayang?" },
  { time: 177.90, text: "Apa kabar wong sing tau tak gawe nyaman?" },
  { time: 181.51, text: "Susah-seneng janjine bebarengan" },
  { time: 185.03, text: "Ning akhire, kowe lunga ninggal kenangan" },
  { time: 189.37, text: "Atiku ra bakal serapuh kuwi" },
  { time: 193.06, text: "Masalah percintaan, tak pikir keri" },
  { time: 197.10, text: "Masa lalu ra perlu tak baleni" },
  { time: 200.62, text: "Teka tenang, kabeh uwis tak gawe lali" },
  { time: 206.49, text: "Apa kabar wong sing tau tak sayang?" },
  { time: 210.28, text: "Apa kabar wong sing tau tak gawe nyaman?" },
  { time: 214.27, text: "Susah-seneng janjine bebarengan" },
  { time: 217.74, text: "Ning akhire, kowe lunga ninggal kenangan" },
  { time: 221.93, text: "Atiku ra bakal serapuh kuwi" },
  { time: 225.45, text: "Masalah percintaan, tak pikir keri" },
  { time: 229.67, text: "Masa lalu ra perlu tak baleni" },
  { time: 233.15, text: "Teka tenang, kabeh uwis tak gawe lali" },
  { time: 240.00, text: "--- Selesai ---" }
];
