// File: banyu surgo.js
lyricsData = [
  { time: 0, text: "--- NDX A.K.A - Banyu Surgo ---" },
  { time: 18.74, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 22.62, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 26.33, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 33.87, text: "Hahaha yooo ndx a.k.a featuring" },
  { time: 38.56, text: "Ndx a.k.a familia karanganyar, men" },
  { time: 42.76, text: "Dangdutan aikonti men (aduh aduh aduh)" },
  { time: 47.31, text: "Yen sedino ora kambon banyu surgo" },
  { time: 50.97, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 54.91, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 61.69, text: "Ayo ngumpul dadi siji, seduluran tekan mati" },
  { time: 65.66, text: "Karanganyar jogjakarta, jangan lupa bahagia" },
  { time: 68.68, text: "Ayo uwul sak kuate, ndene-ndene ayo ngombe" },
  { time: 72.38, text: "Lalekno masalahmu, mending goyang bareng aku" },
  { time: 76.32, text: "Ojo lali campurane, ben ora pengar ciune" },
  { time: 79.23, text: "Penak mabur nang angkasa dikancani banyu surga" },
  { time: 83.17, text: "Nek kowe rumangsa ndx a.k.a familia" },
  { time: 86.77, text: "Ayo mabuk bareng, dunia milik kita bersama" },
  { time: 90.34, text: "Ora eling perkorone yen lagi mumbul-mumbul" },
  { time: 97.36, text: "Ndem-ndeman ngasi tekan wengi, ra nggagas opo wae" },
  { time: 103.72, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 107.87, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 111.59, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 118.17, text: "Yen sedino ora kambon banyu surgo" },
  { time: 121.85, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 125.83, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 132.54, text: "Tresno kui ora penting, ati cidro loro mikir" },
  { time: 136.60, text: "Ngurusi dapuranmu marai ngelu utekku" },
  { time: 139.99, text: "Dituruti opo wae, njaluk mercy tak tembuske" },
  { time: 143.34, text: "Nek rekluna tak nggo dewe, tak gegrepke ciu wae" },
  { time: 148.00, text: "Untung wae ati iki gaweane seng kuoso" },
  { time: 150.95, text: "Cubo nek made in Cino remok pas tok tinggal lungo" },
  { time: 154.09, text: "Akeh wedokan nyeraki aku bingung le milihi" },
  { time: 157.74, text: "Nganti senat senut aduh (pusing pala berbie)" },
  { time: 161.48, text: "Ora eling perkorone yen lagi mumbul-mumbul" },
  { time: 168.32, text: "Ndem-ndeman ngasi tekan wengi, ra nggagas opo wae" },
  { time: 174.87, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 178.56, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 182.87, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 189.13, text: "Yen sedino ora kambon banyu surgo" },
  { time: 193.16, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 197.13, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 203.93, text: "Aku ngombe, kowe ngombe, nek wes penah rasah rese" },
  { time: 207.74, text: "Nek iseh kurang ciune, mending utang basir wae" },
  { time: 211.40, text: "Mbibit taman sak parkire, tambah sing susah batine" },
  { time: 214.71, text: "Rasah nangis mergo tresno, ning sandingmu ono konco" },
  { time: 218.12, text: "Gampang teler pulang kewer, mlakune wes keser-keser" },
  { time: 221.83, text: "Utekku yo melu geser, ndelok dangdut langsung nyawer" },
  { time: 225.13, text: "Teko ngomah balang sapu, bojo nesu aku mlayu" },
  { time: 228.89, text: "Mending aku tuku ciu, ngombe bareng sedulurku" },
  { time: 232.88, text: "Ora eling perkorone yen lagi mumbul-mumbul" },
  { time: 239.57, text: "Ndem-ndeman ngasi tekan wengi, ra nggagas opo wae" },
  { time: 245.96, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 249.90, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 253.63, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 260.55, text: "Yen sedino ora kambon banyu surgo" },
  { time: 264.36, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 268.39, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 275.09, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 278.31, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 282.49, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 288.66, text: "Yen sedino ora kambon banyu surgo" },
  { time: 292.75, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 296.50, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 303.19, text: "Yen sedino ora ngombe banyu pekok" },
  { time: 307.14, text: "Awak rasane lungkrah koyo digebuki" },
  { time: 310.40, text: "Pikirane semrawut dadi soyo ora nggenah" },
  { time: 317.16, text: "Yen sedino ora kambon banyu surgo" },
  { time: 321.09, text: "Malah mung nglangut dewe koyo bocah pekok" },
  { time: 325.18, text: "Uteke dadi mikir bongso perkoro sing ora cetho" },
  { time: 335.00, text: "--- Selesai ---" }
];
