// File: bojoku ketikung.js
lyricsData = [
  { time: 0, text: "--- NDX A.K.A - Bojoku Ketikung ---" },
  { time: 3.68, text: "Jangan opo?" },
  { time: 4.85, text: "Jangan kangkung" },
  { time: 6.89, text: "Tempe opo?" },
  { time: 7.92, text: "Tempe koro" },
  { time: 9.84, text: "Ngopo kok bingung?" },
  { time: 10.98, text: "Bojoku ditikung" },
  { time: 12.75, text: "Popo po ora?" },
  { time: 13.73, text: "Aku ra popo" },
  { time: 14.93, text: "Aku ra nyongko kowe tego karo konco" },
  { time: 20.58, text: "Jarene konco kenthel" },
  { time: 23.35, text: "Bojoku tok sleding tekel" },
  { time: 26.75, text: "Opo ra ono kimcil liyo sing seneng kowe?" },
  { time: 32.57, text: "Nganti kowe nikung bojone koncone dewe" },
  { time: 38.22, text: "He, kowe koncoku, sing jarene CSku" },
  { time: 41.51, text: "Nanging nyatane ning mburi kok kowe koyo pabu" },
  { time: 44.71, text: "Mbribik nikung nyiak bojone konco dewe" },
  { time: 47.74, text: "Ora mikir koncone tumindak sak penake" },
  { time: 50.66, text: "Paitan cangkem lunyu kau merebut pacarku" },
  { time: 53.52, text: "Tusuk dari belakang, ah, mana ku tau" },
  { time: 56.52, text: "Seakan kau arjuna padahal engkau keju" },
  { time: 59.53, text: "Ra ngango sopan santun kau dustai diriku" },
  { time: 63.51, text: "Sak tenane atiku loro" },
  { time: 67.57, text: "Nanging aku mencoba rapopo" },
  { time: 75.42, text: "Sak tenane atiku loro" },
  { time: 79.53, text: "Nanging aku kebacut loro" },
  { time: 86.13, text: "Aku ra nyongko kowe tego karo konco" },
  { time: 92.48, text: "Jarene konco kenthel" },
  { time: 95.55, text: "Bojoku tok sleding tekel" },
  { time: 98.99, text: "Opo ra ono kimcil liyo sing seneng kowe?" },
  { time: 104.44, text: "Nganti kowe nikung bojone koncone dewe" },
  { time: 109.99, text: "Aku kurang opo kok kowe iso tego?" },
  { time: 113.67, text: "Opo ono salahku trus kowe nikung aku?" },
  { time: 116.48, text: "Opo kudu tak jarno kok aku kudu lilo?" },
  { time: 119.58, text: "Ngrasakno tumindakmu sik ngrugekne awakku" },
  { time: 122.60, text: "Pancen kowe konyol, ning utekmu kok protol" },
  { time: 125.63, text: "Pendak ndinone awor, e, bojoku tok gondol" },
  { time: 128.37, text: "Tak bisa aku pendam, mana sangup kutahan" },
  { time: 131.36, text: "Neng ngarep kok apikan, neng mburi kok bajingan" },
  { time: 135.66, text: "Sak tenane atiku loro" },
  { time: 139.81, text: "Nanging aku mencoba rapopo" },
  { time: 147.54, text: "Sak tenane atiku loro" },
  { time: 151.72, text: "Nanging aku kebacut loro" },
  { time: 158.77, text: "Aku ra nyongko kowe tego karo konco" },
  { time: 164.61, text: "Jarene konco kenthel" },
  { time: 167.35, text: "Bojoku tok sleding tekel" },
  { time: 170.78, text: "Opo ra ono kimcil liyo sing seneng kowe?" },
  { time: 176.43, text: "Nganti kowe nikung bojone koncone dewe" },
  { time: 182.29, text: "Yo wis sak karepmu, nek ngeneki caramu" },
  { time: 185.35, text: "Yen wis iki dalane, aku mung ikhlas wae" },
  { time: 188.46, text: "Kowe mung tak titeni, kok watakmu kemlinthi" },
  { time: 191.51, text: "Pacar teman sendiri, kau anggap permaisuri" },
  { time: 194.68, text: "Gek ndang rumat kono, gek ndang untal kono" },
  { time: 197.47, text: "Mugo iso seneng awet tekan tuo" },
  { time: 200.59, text: "Sakjane aku nguyu, mikirke tumindakmu" },
  { time: 203.41, text: "Kok kowe ngragas banget, ngopeni turahanku" },
  { time: 207.60, text: "Sak tenane atiku loro" },
  { time: 211.52, text: "Nanging aku mencoba rapopo" },
  { time: 219.49, text: "Sak tenane atiku loro" },
  { time: 223.66, text: "Nanging aku kebacut loro" },
  { time: 230.72, text: "Aku ra nyongko kowe tego karo konco" },
  { time: 236.33, text: "Jarene konco kenthel" },
  { time: 239.45, text: "Bojoku tok sleding tekel" },
  { time: 242.70, text: "Opo ra ono kimcil liyo sing seneng kowe?" },
  { time: 248.21, text: "Nganti kowe nikung bojone koncone dewe" },
  { time: 254.74, text: "Aku ra nyongko kowe tego karo konco (karo konco)" },
  { time: 260.40, text: "Jarene konco kenthel" },
  { time: 263.35, text: "Bojoku tok sleding tekel (sleding tekel)" },
  { time: 266.72, text: "Opo ra ono kimcil liyo sing seneng kowe? (Seneng kowe)" },
  { time: 272.47, text: "Nganti kowe nikung bojone koncone dewe (koncone dewe)" },
  { time: 285.00, text: "--- Selesai ---" }
];
