// File: bojo galak.js
lyricsData = [
  { time: 0, text: "--- NDX A.K.A - Bojo Galak ---" },
  { time: 1.62, text: "Wis nasibe kudu koyo ngene" },
  { time: 8.91, text: "Nduwe bojo kok ra tahu ngapenake" },
  { time: 17.22, text: "Seneng muring omongane sengak" },
  { time: 24.32, text: "Kudu tak trimo bojoku pancen galak" },
  { time: 31.83, text: "Saben dino rasane ora karuan" },
  { time: 39.71, text: "Ngerasake bojoku sing ra tahu perhatian" },
  { time: 47.53, text: "Nanging piye maneh atiku wes kadung tresno" },
  { time: 55.18, text: "Senajan tak trimo abot ono njero dada" },
  { time: 63.13, text: "Yo wes ben nduwe bojo sing galak" },
  { time: 66.61, text: "Yo wes ben sing omongane sengak" },
  { time: 70.52, text: "Seneng nggawe aku susah" },
  { time: 74.45, text: "Nanging aku wegah pisah" },
  { time: 78.48, text: "Tak tompo nganggo tulus ing ati" },
  { time: 81.63, text: "Tak trimo sliramu tekan saiki" },
  { time: 85.75, text: "Mungkin wes dadi jodone" },
  { time: 90.07, text: "Senajan kahanane koyo ngene" },
  { time: 96.85, text: "Sungguh keterlaluan bojoku sing saiki" },
  { time: 102.00, text: "Kliru sitik wae aku mesti diseneni" },
  { time: 105.83, text: "Ameh dolan ro konco kok ora diolehke" },
  { time: 109.68, text: "Senengane nuduh dikira lungo ro liyane" },
  { time: 113.38, text: "Yen wes ngono aku mung bisa meneng" },
  { time: 117.04, text: "Tak jelasno malah mung nggawe kowe sepaneng" },
  { time: 121.20, text: "Di matamu aku iki ora tahu bener" },
  { time: 124.85, text: "Kabeh mbok salahno rumangsa wes paling pinter" },
  { time: 131.25, text: "Yo wes ben nduwe bojo sing galak" },
  { time: 135.28, text: "Yo wes ben sing omongane sengak" },
  { time: 139.06, text: "Seneng nggawe aku susah" },
  { time: 143.85, text: "Nanging aku wegah pisah" },
  { time: 147.09, text: "Tak tompo nganggo tulus ing ati" },
  { time: 150.92, text: "Tak trimo sliramu tekan saiki" },
  { time: 154.53, text: "Mungkin wes dadi jodone" },
  { time: 158.02, text: "Senajan kahanane koyo ngene" },
  { time: 166.45, text: "Ibarate dele sing uwis dadi tempe" },
  { time: 170.25, text: "Kudu tak lakoni yen pancen ngene dalane" },
  { time: 173.81, text: "Abote nduwe bojo sing galak" },
  { time: 177.66, text: "Lek ra keturutan senengane mencak-mencak" },
  { time: 181.58, text: "Ra usah digetuni aku kudu kuat ati" },
  { time: 185.87, text: "Nganti tekan mati sliramu tetep nang ati" },
  { time: 189.26, text: "Distel kendo wae tak nikmati uripe" },
  { time: 193.33, text: "Senajane galak bojoku pancen sing ayu dhewe" },
  { time: 199.16, text: "Kuat dilakoni lek ra kuat ditinggal ngopi" },
  { time: 205.52, text: "Tetep cinta senajan bojoku galak" },
  { time: 213.71, text: "Yo wes ben nduwe bojo sing galak" },
  { time: 217.61, text: "Yo wes ben sing omongane sengak" },
  { time: 221.84, text: "Seneng nggawe aku susah" },
  { time: 225.25, text: "Nanging aku wegah pisah" },
  { time: 229.77, text: "Tak tompo nganggo tulus ing ati" },
  { time: 232.93, text: "Tak trimo sliramu tekan saiki" },
  { time: 236.92, text: "Mungkin wes dadi jodone" },
  { time: 241.14, text: "Senajan kahanane koyo ngene" },
  { time: 248.43, text: "Yo wes ben nduwe bojo sing galak" },
  { time: 252.46, text: "Yo wes ben sing omongane sengak" },
  { time: 255.96, text: "Seneng nggawe aku susah" },
  { time: 260.03, text: "Nanging aku wegah pisah" },
  { time: 263.62, text: "Tak tompo nganggo tulus ing ati" },
  { time: 267.42, text: "Tak trimo sliramu tekan saiki" },
  { time: 271.42, text: "Mungkin wes dadi jodone" },
  { time: 275.65, text: "Senajan kahanane koyo ngene" },
  { time: 284.00, text: "--- Selesai ---" }
];
