// File: cerito loro.js
lyricsData = [
  { time: 0, text: "--- Happy Asmara - Cerito Loro ---" },
  { time: 22.18, text: "Tak tembangke lagu iki" },
  { time: 28.70, text: "Kanggo sliramu sing paling tak tresnani" },
  { time: 36.39, text: "Getun ati iki aku ra nepati janji" },
  { time: 44.13, text: "Aku lungo tanpo kondo mergo kedanan wong liyo" },
  { time: 56.16, text: "Kelingan mbiyen dewe ketemu" },
  { time: 63.54, text: "Kowe janji ra bakal nglarani atiku" },
  { time: 71.64, text: "Segampang iki caramu mupus roso tresnoku" },
  { time: 78.70, text: "Aku ra bakal lali tekan kapan ra bakal tak ngapurani" },
  { time: 93.79, text: "Kowe lungo ninggal aku atiku loro" },
  { time: 101.37, text: "Ora nyongko kowe gampang keno gudho" },
  { time: 108.83, text: "Aku raiso nompo lehmu dolanan tresno" },
  { time: 116.06, text: "Tak akoni pancen aku iki dudu sopo-sopo" },
  { time: 130.51, text: "Sing gede pangapuramu lungaku ninggal tatu" },
  { time: 138.60, text: "Wes gawe loro atimu" },
  { time: 145.56, text: "Aku ra butuh tresnomu kabeh kuwi mung palsu" },
  { time: 153.71, text: "Tak buang roso tresnoku korban janji manismu" },
  { time: 161.63, text: "Tak jaluk pengertianmu" },
  { time: 165.58, text: "Ojo dadi loromu tulung ngapuranen aku" },
  { time: 176.45, text: "Ati iki dudu dolanan dudu pelampiasan" },
  { time: 184.18, text: "Senajan uripku pas-pasan aku wani kelangan" },
  { time: 192.19, text: "Ora perlu tok getuni cerito loro iki" },
  { time: 392.21, text: ""},
  { time: 200.37, text: "Ora bakal tak baleni" },
  { time: 240.03, text: "Kowe lungo ninggal aku atiku loro" },
  { time: 247.53, text: "Ora nyongko kowe gampang keno gudho" },
  { time: 254.30, text: "Aku raiso nompo lehmu dolanan tresno" },
  { time: 262.09, text: "Tak akoni pancen aku iki dudu sopo-sopo" },
  { time: 275.84, text: "Sing gede pangapuramu lungaku ninggal tatu" },
  { time: 284.45, text: "Wes gawe loro atimu" },
  { time: 291.23, text: "Aku ra butuh tresnomu kabeh kuwi mung palsu" },
  { time: 299.45, text: "Tak buang roso tresnoku korban janji manismu" },
  { time: 307.74, text: "Tak jaluk pengertianmu" },
  { time: 311.26, text: "Ojo dadi loromu tulung ngapuranen aku" },
  { time: 322.15, text: "Ati iki dudu dolanan dudu pelampiasan" },
  { time: 330.28, text: "Senajan uripku pas-pasan aku wani kelangan" },
  { time: 338.00, text: "Ora perlu tok getuni cerito loro iki" },
  { time: 345.42, text: "Ora tak baleni" },
  { time: 353.68, text: "Ora perlu tok getuni cerito loro iki" },
  { time: 362.04, text: "Ora tak baleni" },
  { time: 375.00, text: "--- Selesai ---" }
];
